### ISSUE TITLE
搭建第二套环境的时候出现问题

### ISSUE THREAD

**Issue by JiejieDeng** [shibing624/similarities#25]
CPU类型 Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz

conda环境中安装python 3.10.4

pip install torch==2.1.0
pip install -U similarities
pip install pydantic

执行emb操作时报错了，请帮助我定位一下问题和如何解决，谢谢！

2023-12-31 13:00:41.490 | INFO     | similarities.clip_module:start_multi_process_pool:237 - CUDA is not available. Start 4 CPU worker
2023-12-31 13:00:41.491 | INFO     | similarities.clip_module:start_multi_process_pool:240 - Start multi-process pool on devices: cpu, cpu, cpu, cpu
2023-12-31 13:00:58.630 | DEBUG    | similarities.clip_module:encode_multi_process:297 - Chunk data into 40 packages of size 250
Token indices sequence length is longer than the specified maximum sequence length for this model (89 > 77). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (92 > 77). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (90 > 77). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (89 > 77). Running this sequence through the model will result in indexing errors
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 327, in _encode_multi_process_worker
    embeddings = model.encode(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 203, in encode
    out_features = self.forward(features)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 73, in forward
    text_outputs = self.model.text_model(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 691, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 219, in forward
    embeddings = inputs_embeds + position_embeddings
RuntimeError: The size of tensor a (92) must match the size of tensor b (77) at non-singleton dimension 1
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 327, in _encode_multi_process_worker
    embeddings = model.encode(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 203, in encode
    out_features = self.forward(features)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 73, in forward
    text_outputs = self.model.text_model(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 691, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 219, in forward
    embeddings = inputs_embeds + position_embeddings
RuntimeError: The size of tensor a (89) must match the size of tensor b (77) at non-singleton dimension 1
Process SpawnProcess-1:
Process SpawnProcess-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 327, in _encode_multi_process_worker
    embeddings = model.encode(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 203, in encode
    out_features = self.forward(features)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 327, in _encode_multi_process_worker
    embeddings = model.encode(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 203, in encode
    out_features = self.forward(features)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 73, in forward
    text_outputs = self.model.text_model(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 691, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 219, in forward
    embeddings = inputs_embeds + position_embeddings
RuntimeError: The size of tensor a (90) must match the size of tensor b (77) at non-singleton dimension 1
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/similarities/clip_module.py", line 73, in forward
    text_outputs = self.model.text_model(
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 691, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/similarities/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 219, in forward
    embeddings = inputs_embeds + position_embeddings
RuntimeError: The size of tensor a (89) must match the size of tensor b (77) at non-singleton dimension 1

**Comment by shibing624** [comment]
用gpu跑clip的emb。cpu太慢，如果有问题，单卡跑看看

**Comment by JiejieDeng** [comment]
> 用gpu跑clip的emb。cpu太慢，如果有问题，单卡跑看看

嗯，换显卡是一种办法。有提示这种报错，但是程序没有完全中断，我尝试修改代码试试，网上这种报错还是挺多的。
