### ISSUE TITLE
运行faiss_bert_search_server_demo.py时报错

### ISSUE THREAD

**Issue by shaojianbo13** [shibing624/similarities#36]
运行faiss_bert_search_server_demo.py文件时报错，显示尝试读取 bert_engine/text_emb/ 文件夹中的嵌入文件时，未能找到任何嵌入文件，是什么原因，是需要额外配置什么吗。
![Uploading 微信图片_20240710135048.png…]()

**Comment by shaojianbo13** [comment]
2024-07-10 13:43:35,356 [INFO]: >>> Finished "Reading total number of vectors and dimension" in 0.2019 secs
2024-07-10 13:43:35,356 [INFO]: >>> Finished "Launching the whole pipeline" in 0.2021 secs
2024-07-10 13:43:35.356 | ERROR    | similarities.faiss_bert_similarity:bert_index:132 - Index bert_engine/text_emb/ failed, No embeddings found in folder bert_engine/text_emb/
Traceback (most recent call last):
  File "E:\project\similarities-main\examples\faiss_bert_search_server_demo.py", line 68, in <module>
    main()
  File "E:\project\similarities-main\examples\faiss_bert_search_server_demo.py", line 37, in main
    nb_cores=None,
  File "E:\project\similarities-main\similarities\faiss_bert_similarity.py", line 133, in bert_index
    raise e
  File "E:\project\similarities-main\similarities\faiss_bert_similarity.py", line 128, in bert_index
    use_gpu=use_gpu,
  File "E:\ana\envs\torch_GPU\lib\site-packages\autofaiss\external\quantize.py", line 209, in build_index
    meta_columns=id_columns,
  File "E:\ana\envs\torch_GPU\lib\site-packages\embedding_reader\embedding_reader.py", line 20, in __init__
    self.reader = NumpyReader(embeddings_folder)
  File "E:\ana\envs\torch_GPU\lib\site-packages\embedding_reader\numpy_reader.py", line 77, in __init__
    raise ValueError(f"No embeddings found in folder {embeddings_folder}")
ValueError: No embeddings found in folder bert_engine/text_emb/
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

**Comment by shibing624** [comment]
git clone https://github.com/shibing624/similarities
cd 到examples目录，再执行：python faiss_bert_search_server_demo.py

**Comment by shaojianbo13** [comment]
> git clone https://github.com/shibing624/similarities cd 到examples目录，再执行：python faiss_bert_search_server_demo.py

我是直接pycharm在faiss_bert_search_server_demo.py文件下运行的

**Comment by shaojianbo13** [comment]
> git clone https://github.com/shibing624/similarities cd 到examples目录，再执行：python faiss_bert_search_server_demo.py

传给EmbeddingReader中embeddings_folder是bert_engine/text_emb/这个路径对吗

**Comment by shibing624** [comment]
是，参考示例来
