### ISSUE TITLE
pip安装后无法运行demo，直接报错

### ISSUE THREAD

**Issue by yxw2014** [shibing624/similarities#9]
### Describe the bug
pip安装后无法运行demo，直接报错：
 pip install -U similarities

**运行代码：**

`from similarities import Similarity

m = Similarity()
r = m.similarity('如何更换花呗绑定银行卡', '花呗更改绑定银行卡')
print(f"similarity score: {float(r)}")  # similarity score: 0.855146050453186`

**报错信息：**
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1172, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 42, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/modeling_utils.py", line 84, in <module>
    from accelerate import __version__ as accelerate_version
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/accelerate/accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/accelerate/tracking.py", line 49, in <module>
    import wandb
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/__init__.py", line 5, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/wandb_artifacts.py", line 33, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/apis/__init__.py", line 42, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/apis/internal.py", line 1, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 45, in <module>
    from ..lib import retry
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 10, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/proto/wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/proto/v3/wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/proto/wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/proto/v3/wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yexinwei/Desktop/www/src/openai/text.py", line 1, in <module>
    from similarities import Similarity
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/similarities/__init__.py", line 11, in <module>
    from similarities.similarity import Similarity
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/similarities/similarity.py", line 17, in <module>
    from text2vec import SentenceModel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/text2vec/__init__.py", line 17, in <module>
    from text2vec.bertmatching_model import BertMatchModel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/text2vec/bertmatching_model.py", line 16, in <module>
    from transformers import BertForSequenceClassification, BertTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1163, in __getattr__
    value = getattr(module, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1162, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1174, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
'NoneType' object has no attribute 'message_types_by_name'`

**Comment by shibing624** [comment]
这个出错不是在  wandb 吗？

```
from wandb.proto.v3.wandb_base_pb2 import *
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/proto/v3/wandb_base_pb2.py", line 21, in
__RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

pip uninstall wandb

**Comment by yxw2014** [comment]
pip uninstall wandb 后解决了， 谢谢！
